version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - lumen
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../lumen:/var/www/html/lumen
    container_name: nginx-muscle
  lumen:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ../../lumen:/var/www/html/lumen
    container_name: php-fpm-lumen
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: musclebeauty!
      MYSQL_USER: muscle-user
      MYSQL_PASSWORD: hi-muscle-muscle
      MYAQL_DATABASE: grpcserver
    container_name: mysql-grpcserver
